### ISSUE TITLE
toml不能直接转换的原因可能是只能存储key-value形式的

### ISSUE THREAD

**Issue by Bear-V** [tyr-rust-bootcamp/01-rcli#6]
```rust
OutputFormat::Toml => {
            // toml 只能以 key-value 的形式存储数据
            let mut obj = HashMap::new();
            obj.insert("data", ret);
            toml::to_string_pretty(&obj)?
        }
```
我改成这样就可以的运行了
出来数据是这样的
```toml
[[data]]
DOB = "Dec 10, 1987 (31)"
"Kit Number" = "21"
Name = "Gonzalo Higuaín"
Nationality = "Argentina"
Position = "Centre-Forward"

[[data]]
DOB = "May 21, 1986 (33)"
"Kit Number" = "17"
Name = "Mario Mandzukic"
Nationality = "Croatia"
Position = "Centre-Forward"

```

不知道老师有没有更好的办法
或者说
toml确实只能存储key-value形式的文本
